name: Release App

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

jobs:
  build-and-release:
    runs-on: macos-latest # Using macOS runner for macOS build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true
      
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build macOS app
        run: |
          flutter config --enable-macos-desktop
          flutter build macos --release
          
      - name: Create DMG
        run: |
          brew install create-dmg
          create-dmg \
            --volname "Android File Transfer" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "Android File Transfer.app" 200 190 \
            --hide-extension "Android File Transfer.app" \
            --app-drop-link 600 185 \
            "Android File Transfer.dmg" \
            "build/macos/Build/Products/Release/Android File Transfer.app"

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            Android File Transfer.dmg
          body: |
            ## Android File Transfer for macOS ${{ env.VERSION }}
            
            A modern, user-friendly alternative to Android File Transfer for macOS users, built with Flutter.
            
            ### Installation
            1. Download the DMG file
            2. Open the DMG file
            3. Drag the app to your Applications folder
            4. Launch the app from Applications
            
            ### Requirements
            - macOS 10.15 or later
            - Android device with USB debugging enabled
            
            ### Changes in this version
            - Please check the commit history for detailed changes
            
            ### Note
            This is an open-source project for educational purposes. Feel free to contribute! 